{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.controller.fullname" . }}-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.controller.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pinot-controller.conf: |-
    controller.helix.cluster.name={{ .Values.cluster.name }}
    controller.port={{ .Values.controller.port }}
    controller.vip.host={{ include "pinot.controller.fullname" . }}
    controller.vip.port={{ .Values.controller.service.port }}
    controller.data.dir={{ .Values.controller.data.dir }}
    controller.zk.str={{ include "zookeeper.path" . }}
    pinot.set.instance.id.to.hostname=true
{{- end }}
