{{- if .Values.minion.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.minion.fullname" . }}-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.minion.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  pinot-minion.conf: |-
    pinot.minion.port={{ .Values.minion.port }}
{{- end }}
