{{- if .Values.minion.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.minion.fullname" . }}-jmx-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.minion.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus-pinot-minion.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.minion.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+).authorization\"><>(\\w+)"
        name: "pinot_minion_authorization_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.documentsScanned\"><>(\\w+)"
        name: "pinot_minion_documentsScanned_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.entriesScannedInFilter\"><>(\\w+)"
        name: "pinot_minion_entriesScannedInFilter_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.entriesScannedPostFilter\"><>(\\w+)"
        name: "pinot_minion_entriesScannedPostFilter_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.freshnessLagMs\"><>(\\w+)"
        name: "pinot_minion_freshnessLagMs_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.queries\"><>(\\w+)"
        name: "pinot_minion_queries_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.queryExecution\"><>(\\w+)"
        name: "pinot_minion_queryExecution_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.queryRouting\"><>(\\w+)"
        name: "pinot_minion_queryRouting_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.reduce\"><>(\\w+)"
        name: "pinot_minion_reduce_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.requestCompilation\"><>(\\w+)"
        name: "pinot_minion_requestCompilation_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.scatterGather\"><>(\\w+)"
        name: "pinot_minion_scatterGather_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)\\.totalServerResponseSize\"><>(\\w+)"
        name: "pinot_minion_totalServerResponseSize_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)_(\\w+).groupBySize\"><>(\\w+)"
        name: "pinot_minion_groupBySize_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)_(\\w+).noServingHostForSegment\"><>(\\w+)"
        name: "pinot_minion_noServingHostForSegment_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.healthcheck(\\w+)\"><>(\\w+)"
        name: "pinot_minion_healthcheck_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.helix.(\\w+)\"><>(\\w+)"
        name: "pinot_minion_helix_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.helixZookeeper(\\w+)\"><>(\\w+)"
        name: "pinot_minion_helix_zookeeper_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.nettyConnection(\\w+)\"><>(\\w+)"
        name: "pinot_minion_nettyConnection_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.clusterChangeCheck\"\"><>(\\w+)"
        name: "pinot_minion_clusterChangeCheck_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.proactiveClusterChangeCheck\"><>(\\w+)"
        name: "pinot_minion_proactiveClusterChangeCheck_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.(\\w+)Exceptions\"><>(\\w+)"
        name: "pinot_minion_exceptions_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"MinionMetrics\", name=\"pinot.minion.routingTableUpdateTime\"><>(\\w+)"
        name: "pinot_minion_routingTableUpdateTime_$1"
{{- end }}
